title: "Mohammed Abdallah — Accountant (UAE)"
description: "Portfolio & Blog: UAE VAT • ERP (QuickBooks, Odoo, SAP FI) • Excel"
lang: en

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

minimal_mistakes_skin: "default"

author:
  name: "Mohammed Abdallah"

# لازم السطر ده عشان الصفحات اللي جوه _pages تشتغل
include: [_pages]
